# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sebavaro <sebavaro@student.42angouleme.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/10/13 14:49:47 by sebavaro          #+#    #+#              #
#    Updated: 2026/02/01 11:57:37 by sebavaro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CFILES = ft_isalpha.c\
	 ft_isdigit.c\
	 ft_isalnum.c\
	 ft_isascii.c\
	 ft_isprint.c\
	 ft_strlen.c\
	 ft_bzero.c\
	 ft_memset.c\
	 ft_memcpy.c\
	 ft_memmove.c\
	 ft_strlcpy.c\
	 ft_strlcat.c\
	 ft_toupper.c\
	 ft_tolower.c\
	 ft_strchr.c\
	 ft_strrchr.c\
	 ft_strncmp.c\
	 ft_memchr.c\
	 ft_memcmp.c\
	 ft_strnstr.c\
	 ft_atoi.c\
	 ft_calloc.c\
	 ft_strdup.c\
	 ft_substr.c\
	 ft_strjoin.c\
	 ft_strtrim.c\
	 ft_split.c\
	 ft_itoa.c\
	 ft_strmapi.c\
	 ft_striteri.c\
	 ft_putchar_fd.c\
	 ft_putstr_fd.c\
	 ft_putendl_fd.c\
	 ft_putnbr_fd.c\
	 ft_atol.c

CBONUS = ft_lstnew_bonus.c\
	ft_lstadd_front_bonus.c\
	ft_lstsize_bonus.c\
	ft_lstlast_bonus.c\
	ft_lstadd_back_bonus.c\
	ft_lstdelone_bonus.c\
	ft_lstclear_bonus.c\
	ft_lstiter_bonus.c\
	ft_lstmap_bonus.c

OBJS = $(CFILES:.c=.o)

OBJS_BONUS = $(CBONUS:.c=.o)

CC = clang

CFLAGS = -Wall -Werror -Wextra

all : $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

bonus : $(OBJS) $(OBJS_BONUS)
	ar rcs $(NAME) $(OBJS) $(OBJS_BONUS)

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@ -I.  

clean :
	rm -f $(OBJS) $(OBJS_BONUS)

fclean : clean
	rm -f $(NAME)

re : fclean all bonus

.PHONY: all bonus clean fclean re
